### ISSUE TITLE
Issue with numpy versions?

### ISSUE THREAD

**Issue by bbimber** [lilab-bcb/demuxEM#15]
Hello -

I dont know if the pegasusio repo is monitored (there's almost no issues), so apologies for cross-posting here. I think there's a compatibility issue with demuxEM/pegasusio and the latest numpy releases. See here for more specifics and an associated PR that might fix this: https://github.com/lilab-bcb/pegasusio/issues/100.

**Comment by yihming** [comment]
Hello @bbimber . Your [PR](https://github.com/lilab-bcb/pegasusio/pull/101) in PegasusIO has been merged and reflected in PegasusIO v0.8.0.
